/*
const cmpahistory =
[{
    "IncidentID": 37949,
    "IncidentDate": "6/21/2021",
    "EntryDate": "7/12/2021",
    "Division": "ROUTINE-ALT",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "Final CM.\r\n\r\nLDW 6/15/2020\r\n\r\n \r\n\r\nNuvia has been on a Personal leave of absence beginning on 06/16/2020.  Nuvia came in on 08-10-2020 and requested another leave of absence . Nuvia has not made any contact with HR Manager Mona Lee or Supervisor Tawana Marshall since 08-10-2020. Nuvia came into the office on 06-14-2021 to speak to Supervisor regarding needing to take another personal leave of absence. Supervisor Tawana Marshall  directed Nuvia to the HR Manager Mona Lee.  Nuvia has not made any contact during her last leave of absence regarding her status to return back to work.  The company has decided that the leave of absence with not be extended as per company policy, PLOA\u0027s are not to be extended over 90 days, and also she has not made any attempt to contact HRM or supervisor since 8/10/20.\r\n\r\nDue to Nuvia current situation and unable to work at this time . Nuvia is resigning and will not be eligible for rehire.\r\n\r\n \r\n\r\nReason:  Not returning from personal LOA after 12 months. \r\n\r\nLDW 6/15/20. \r\n\r\nTerm Date:  6/14/2021",
    "EmployeeComments": null,
    "Manager": "Lee, Mona",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "7/12/2021",
    "Points": 0,
    "SupervisorFinished": "7/12/2021",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 35560,
    "IncidentDate": "8/9/2020",
    "EntryDate": "9/4/2020",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "Driver no call no show\r\n\r\nReference id#35560\r\n\r\nDriver is on a leave of absence beginning 08-07-2020.\r\n\r\nClosed TM",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "9/4/2020",
    "Points": 0,
    "SupervisorFinished": "8/10/2020",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 35554,
    "IncidentDate": "8/8/2020",
    "EntryDate": "9/4/2020",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Errors and Omissions",
    "IncidentDescription": "Driver Nuvia (ACEN) NO CALL NO SHOW. First PU @ 3:30 for 4:00 Appt. \r\n\r\nReference id#35554\r\n\r\nDriver is on a leave of absence beginning 08-07-2020.\r\n\r\nClosed TM",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "9/4/2020",
    "Points": 0,
    "SupervisorFinished": "8/10/2020",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 34553,
    "IncidentDate": "5/16/2020",
    "EntryDate": "5/19/2020",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "Driver Nuvia (ACEN) Route W1. NO CALL NO SHOW. First pick up @03:15 for 04:00 Appt. Zello twice No Answer\r\n\r\nReference id#34553\r\n\r\nError - Driver weekend was scheduled to be covered. Documentation was entered into the Admin Calendar on 05-04-2020.  Driver will not be held accountable to receive any cm points .\r\n\r\nClosed TM",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "5/19/2020",
    "Points": 0,
    "SupervisorFinished": "5/19/2020",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 34424,
    "IncidentDate": "5/6/2020",
    "EntryDate": "5/12/2020",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "NO CALL NO SHOW FOR DRIVER ACEN  1ST P/U AT 5:00AM\r\n\r\nReference id#34424\r\n\r\nThis is Supervisor Tawana Marshall error. Driver Nuvia Acevedo requested day off on 03-15-2020. Supervisor forgot to add to the off calendar.\r\n\r\nClosed TM",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "5/12/2020",
    "Points": 0,
    "SupervisorFinished": "5/6/2020",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 32275,
    "IncidentDate": "12/17/2019",
    "EntryDate": "2/6/2020",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Absence",
    "IncidentDescription": "Mom having surgery \r\n\r\nReference id#32275\r\n\r\nThis is continuation from Reference id#32276 duplicate transport. Please reference id#32276",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "2/6/2020",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Attendance"
}, {
    "IncidentID": 32276,
    "IncidentDate": "12/17/2019",
    "EntryDate": "2/6/2020",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Errors and Omissions",
    "IncidentDescription": "driver acen works from 0430-1630 with a pick up at 0544. She sent a driver alert to call off her Mom is having surgery\r\n\r\nReference id#32276\r\n\r\nDriver Nuvia Acevedo come to complete partial route as advised by Supervisor . Supervisor sent driver home due to her mom having a emergency surgery. Closed TM",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "2/6/2020",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 31557,
    "IncidentDate": "10/31/2019",
    "EntryDate": "11/6/2019",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Speed Alert",
    "IncidentDescription": "697 Location: Pearl Harbor Memorial Hwy, Maricopa, AZ 85138 - Speed: 77 mph - Time: Oct 31 2019 7:36AM\r\n\r\nReference id#31557\r\n\r\nDriver has not received a speed alert in over 5 months . This  will be documented as a warning . If further incidents occurs, there will be further consequences up to including termination. Closed TM",
    "EmployeeComments": null,
    "Manager": "Marshall, Tawana",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "6/25/2021",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Vehicle"
}, {
    "IncidentID": 30095,
    "IncidentDate": "7/16/2019",
    "EntryDate": "9/17/2019",
    "Division": "ROUTINE-ALT",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "Supervisor Tawana Marshall received a Drive Cam Safety notification . \r\n\r\nSupervisor Tawana Marshall spoke to Driver Nuvia Acevedo .  Nuvia advised Supervisor that she was looking at her GPS instead of listening to the directions . Supervisor Tawana Marshall let Nuvia kow to utilize her map book and also try to listen to the GPS or Bluetooth it through the company vehicle safety is our first priority.  This will be documented as a warning . If further of this actions continues there will be further consequences up to including termination. Closed TM\r\n",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "9/17/2019",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 28884,
    "IncidentDate": "5/18/2019",
    "EntryDate": "5/30/2019",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Speed Alert",
    "IncidentDescription": "707 Location: Beeline Hwy, Tortilla Flat, AZ 85190 - Speed: 78 mph - Time: May 18 2019 8:28AM\r\n\r\n\r\nReference id#28884\r\n\r\nDriver Nuvia Acevedo received a speed alert on 05-18-2019. Nuvia has not received a speed alert since 12-20-2018. This will be documented as a warning there will be no cm points assigned . If further of this action continues, there will be further consequences up to including termination. Closed TM\r\n\r\n",
    "EmployeeComments": null,
    "Manager": "La Puma, Salvatore",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "5/30/2019",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Vehicle"
}, {
    "IncidentID": 26855,
    "IncidentDate": "12/20/2018",
    "EntryDate": "5/30/2019",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Speed Alert",
    "IncidentDescription": "650 Location: Pearl Harbor Memorial Hwy, Casa Grande, AZ 85122 - Speed: 77 mph - Time: Dec 20 2018 7:07AM\r\n\r\nSee Map \u003chttp://app.tsomobile.com/?act=EMALATLNG\u0026pd=238195127\u0026f1=32.897621\u0026f2=-111.687019#custommap\u003e  \r\n\r\nReference id#26855\r\n\r\nNuvia Acevedo has not received a speed alert since 12-07-2017. This will be documented as a warning . If further of these actions occur, there will be further consequences up to including termination. Closed TM\r\n\r\n\r\n",
    "EmployeeComments": null,
    "Manager": "La Puma, Salvatore",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "5/30/2019",
    "Points": 0,
    "SupervisorFinished": "3/14/2019",
    "IncidentType": "Vehicle"
}, {
    "IncidentID": 23789,
    "IncidentDate": "6/25/2018",
    "EntryDate": "8/6/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Missing DCS Visit Note",
    "IncidentDescription": "Missing visit note for Ref # M2818 for visit date of 06/25/2018\r\n\r\nReference id# 23789\r\n\r\nNo cm points will be assigned ",
    "EmployeeComments": null,
    "Manager": "Cruz, Caroline",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "8/6/2018",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Non-Driver Disciplinary"
}, {
    "IncidentID": 23311,
    "IncidentDate": "5/30/2018",
    "EntryDate": "8/6/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Missing DCS Visit Note",
    "IncidentDescription": "Missing visit note for Ref # M2699 for visit date of 05/30/2018\r\n\r\nReference id#23311\r\n\r\nIncorrect date for note. Date has been updated.",
    "EmployeeComments": null,
    "Manager": "Cruz, Caroline",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "8/6/2018",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Non-Driver Disciplinary"
}, {
    "IncidentID": 22729,
    "IncidentDate": "5/4/2018",
    "EntryDate": "5/7/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Missing DCS Visit Note",
    "IncidentDescription": "Missing visit note for Ref # M2818 for visit date of 05/04/2018\r\n\r\nReference id#22729\r\n\r\nNo CM Points assigned.",
    "EmployeeComments": null,
    "Manager": "Cruz, Caroline",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "5/7/2018",
    "Points": 0,
    "SupervisorFinished": "5/7/2018",
    "IncidentType": "Non-Driver Disciplinary"
}, {
    "IncidentID": 22185,
    "IncidentDate": "4/6/2018",
    "EntryDate": "4/9/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Missing DCS Visit Note",
    "IncidentDescription": "Missing visit note for Ref # M2498 for visit date of 04/06/2018\r\n\r\nReference id#22185\r\n\r\nNote was submitted on 4-07-2018. Incorrect date was entered . There will be no cm points assigned.",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "4/9/2018",
    "Points": 0,
    "SupervisorFinished": "4/9/2018",
    "IncidentType": "Non-Driver Disciplinary"
}, {
    "IncidentID": 22045,
    "IncidentDate": "3/30/2018",
    "EntryDate": "4/9/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Missing DCS Visit Note",
    "IncidentDescription": "Missing visit note for Ref # M2498 for visit date of 03/30/2018\r\n\r\nReference id#22045\r\n\r\nSystem was down no cm points assigned.",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "4/9/2018",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Non-Driver Disciplinary"
}, {
    "IncidentID": 21639,
    "IncidentDate": "3/9/2018",
    "EntryDate": "4/9/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Missing DCS Visit Note",
    "IncidentDescription": "Missing visit note for Ref # M2498 for visit date of 03/09/2018\r\n\r\nReference id#21639\r\n\r\nNo cm points assigned",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "4/9/2018",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Non-Driver Disciplinary"
}, {
    "IncidentID": 21612,
    "IncidentDate": "3/7/2018",
    "EntryDate": "4/9/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Missing DCS Visit Note",
    "IncidentDescription": "Missing visit note for Ref # M2498 for visit date of 03/07/2018\r\n\r\nReference id#21612\r\n\r\nThere will be no cm points assigned.",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "4/9/2018",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Non-Driver Disciplinary"
}, {
    "IncidentID": 21162,
    "IncidentDate": "2/16/2018",
    "EntryDate": "4/9/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Missing DCS Visit Note",
    "IncidentDescription": "Missing visit note for Ref # M2498 for visit date of 02/16/2018\r\n\r\nReference id#21162\r\n\r\nCase Aide Nuvia Acevedo note was submitted in a timely manner. There will be no points assigned.",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "4/9/2018",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Non-Driver Disciplinary"
}, {
    "IncidentID": 20877,
    "IncidentDate": "2/5/2018",
    "EntryDate": "2/5/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Errors and Omissions",
    "IncidentDescription": "driver called off. flag her route\r\n\r\nReference id# 20877\r\n\r\nCase Aide Nuvia Acevedo contacted her Supervisor Tawana Scott on 02-04-2018 at 19:28 via text message with a note from the Doctor stating that she has pink eye. Case Aide note states that she is to not return to work until 02-06-2018.",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "2/5/2018",
    "Points": 0,
    "SupervisorFinished": "2/5/2018",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 20861,
    "IncidentDate": "2/2/2018",
    "EntryDate": "2/5/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Missing DCS Visit Note",
    "IncidentDescription": "Missing visit note for Ref # M2498 for visit date of 02/02/2018\r\n\r\nReference id# 20861\r\n\r\nNo points will be assigend .",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "2/5/2018",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Non-Driver Disciplinary"
}, {
    "IncidentID": 20665,
    "IncidentDate": "1/24/2018",
    "EntryDate": "2/1/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Missing DCS Visit Note",
    "IncidentDescription": "Missing visit note for Ref # M2636 for visit date of 01/24/2018\r\n\r\nReference id#20665\r\n\r\nNote was submitted but was archived. There will be no points assigned.",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "2/1/2018",
    "Points": 0,
    "SupervisorFinished": "1/31/2018",
    "IncidentType": "Non-Driver Disciplinary"
}, {
    "IncidentID": 20470,
    "IncidentDate": "1/12/2018",
    "EntryDate": "1/16/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Missing DCS Visit Note",
    "IncidentDescription": "Missing visit note for Ref # M2498 for visit date of 01/12/2018\r\n\r\nReference id#20470\r\n\r\nCase Aide Nuvia will receive one cm point for not completing her note within the 24 hour required time. Case Aide is aware of the allow time that the visitation note is required to be submitted . If further of this occurs, there will be further consequences. ",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "1/16/2018",
    "Points": 10,
    "SupervisorFinished": "1/15/2018",
    "IncidentType": "Non-Driver Disciplinary"
}, {
    "IncidentID": 20324,
    "IncidentDate": "1/5/2018",
    "EntryDate": "1/16/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Missing DCS Visit Note",
    "IncidentDescription": "Missing visit note for Ref # M2498 for visit date of 01/05/2018\r\n\r\nReference id#20324\r\n\r\nNote was completed on time. There will be no points assigned.",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "1/16/2018",
    "Points": 0,
    "SupervisorFinished": "1/9/2018",
    "IncidentType": "Non-Driver Disciplinary"
}, {
    "IncidentID": 20102,
    "IncidentDate": "12/26/2017",
    "EntryDate": "1/16/2018",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Warning",
    "IncidentDescription": "DRIVER CALLED OFF\r\n\r\nReference id#20102\r\n\r\nCase Aide Nuvia contacted Supervisor Tawana Scott on 12-25-2017 stating that she is not feeling well. Case Aide will not be assigned any points due to contacting more than 6 hours prior to her shift start time. ",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "1/16/2018",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 19703,
    "IncidentDate": "12/1/2017",
    "EntryDate": "12/8/2017",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Speed Alert",
    "IncidentDescription": "722 Location: Arizona Veterans Memorial Hwy, New River, AZ 85087 - Speed: 76 mph - Time: Dec 1 2017 1:26PM\r\n\r\nSee Map \u003chttp://www.tsomobile.net/CustomMap.aspx?act=EMALATLNG\u0026pd=185006849\u0026f1=33.994450\u0026f2=-112.133904\u003e \r\n\r\nReference id# 19703\r\n\r\nCase Aide Nuvia Acevedo was advised to change vehicles with Driver Martin Rosenberger due to the Resource Department not having any available vehicles for the capacity of children that he needed to transport. Nuvia was not the driver in this vehicle at this time. There will be no points assigned .",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "12/8/2017",
    "Points": 0,
    "SupervisorFinished": "12/8/2017",
    "IncidentType": "Vehicle"
}, {
    "IncidentID": 15387,
    "IncidentDate": "9/7/2016",
    "EntryDate": "9/14/2016",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Errors and Omissions",
    "IncidentDescription": "driver has no signatures uploaded need to have before she turns off cell phone. please talk to her to check with dispatch at the end of the day. send a drive alert to be cleared.\r\n\r\nReference id#15387\r\n\r\nThis is a invalid CMPA. Case Aide Nuvia was contacted who was still supervising a visit until 1800pm. It looks like she was done with her route for the day due to she does not return the child after the visit. The return from the child who she supervises after the visit is transported by another driver who works with ComTrans. ",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "9/14/2016",
    "Points": 0,
    "SupervisorFinished": "9/8/2016",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 13897,
    "IncidentDate": "5/3/2016",
    "EntryDate": "5/4/2016",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Vehicle accident - did recieve citation and did report to manager (minor)",
    "IncidentDescription": "Our driver was west bound on Southern Avenue and turned into the center turning lane to make a left turn on 6th Avenue. The other party crossed three lanes of stopped traffic to make a left turn on east bound southern Avenue and hit our passenger side front tire.",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "5/4/2016",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Vehicle"
}, {
    "IncidentID": 13900,
    "IncidentDate": "5/3/2016",
    "EntryDate": "5/16/2016",
    "Division": "ROUTINE-ALT",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "Nuvia was involved in a non at fault accident on 05-03-2016. The other driver fled the scene of the accident and contacted Comtrans. Safety Program Manager Robert Morrone spoke to the other driver who admitted that she crossed over into Nuvia lane and rub against the company vehicle. Safety Program Manager states that Nuvia is not responsible . Nuvia will be reminded to call the police as soon as any accident happens then to contact dispatch to make them aware of the incident once it occurs.",
    "EmployeeComments": null,
    "Manager": "Chaney, Danelle",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "5/16/2016",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 13216,
    "IncidentDate": "3/2/2016",
    "EntryDate": "3/30/2016",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "I cannot reach Nuvia to check her in. It was time to flag her route and Ricardo told me that he had seen her earlier. I am not flagging her route.",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "3/30/2016",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 13063,
    "IncidentDate": "2/16/2016",
    "EntryDate": "3/7/2016",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "Cannot reach driver/flagged route",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "3/7/2016",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 12918,
    "IncidentDate": "1/29/2016",
    "EntryDate": "3/30/2016",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "Driver left car seats in vehicle. Car seats were carried in by lot attendant Matt after checking vehciles. A text was sent out erlier in the day that car seats need to be brought in and vehciles would be checked this evening. Please advise this driver that car seats should be brought in daily to make use for others drivers in need. ",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "3/30/2016",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 12739,
    "IncidentDate": "1/8/2016",
    "EntryDate": "3/30/2016",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "Note is regarding Driver ACEN. I could not contact driver on both Work or personal phone. Driver needs update on personal phone number.",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "3/30/2016",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 11911,
    "IncidentDate": "9/18/2015",
    "EntryDate": "11/19/2015",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Positive Feedback from Customer",
    "IncidentDescription": "Kimberly Myers, a CPS customer, called to request that Nuvia be sent to pick her up as often as possible. The client stated that Nuvia was extrememly curtious and espectful to her and loved the way she was treated by Nuvia. Great job Nuvia!",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "11/19/2015",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 11691,
    "IncidentDate": "8/18/2015",
    "EntryDate": "11/19/2015",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Errors and Omissions",
    "IncidentDescription": "Nuvia,, Driver \"ACEN\" disconnected the line with me after I requested her times and miles because she advised me she had been running late to a pick up and supposedly about to enter them. . I then called back Nuvia thinking this was by accident, the driver did not answer my call. Nuvia... Please enter times and miles asap daily.This delay causes client items to apear late or not picked up in the \"Late pick-up\" when the driver is possibly already in route with the client aboard. Leaving dispatchers to think the driver has not picked up the client and causing uneccesary calling of drivers to occur.",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "11/19/2015",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 11404,
    "IncidentDate": "7/9/2015",
    "EntryDate": "7/22/2015",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Lack of judgement/responsibility",
    "IncidentDescription": "Nuvia showed up on the speed alert on 07-09-2015 going 77mph. Nuvia will receive 1 cm point ",
    "EmployeeComments": null,
    "Manager": "Boris, Kolby",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "7/22/2015",
    "Points": 10,
    "SupervisorFinished": "",
    "IncidentType": "General Conduct"
}, {
    "IncidentID": 11202,
    "IncidentDate": "6/11/2015",
    "EntryDate": "6/24/2015",
    "Division": "ROUTINE-ALT",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Lack of judgement/responsibility",
    "IncidentDescription": "Nuvia showing on the speed alert going 77mph is a 75mph speed limit. Driver is aware that she is not required to drive past the required speed limit by law. Driver will receive 1 cm point.",
    "EmployeeComments": null,
    "Manager": "Boris, Kolby",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "6/24/2015",
    "Points": 10,
    "SupervisorFinished": "",
    "IncidentType": "General Conduct"
}, {
    "IncidentID": 11001,
    "IncidentDate": "5/19/2015",
    "EntryDate": "6/2/2015",
    "Division": "ROUTINE-ALT",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Lack of judgement/responsibility",
    "IncidentDescription": "Nuvia showed up on the speed alert on 05-19-2015 going 77mph. Nuvia will receive 1 cm point .Nuvia will not be eligible for the safety bonus. Nuvia will be reminded that she is not to exceed the required speed limit by law. Future violations will result in further consequences up to including termination.",
    "EmployeeComments": null,
    "Manager": "Boris, Kolby",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "6/2/2015",
    "Points": 10,
    "SupervisorFinished": "",
    "IncidentType": "General Conduct"
}, {
    "IncidentID": 8670,
    "IncidentDate": "7/18/2014",
    "EntryDate": "7/25/2014",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "Did not clear with dispatch. Did not clock in or out",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "7/25/2014",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 8618,
    "IncidentDate": "7/14/2014",
    "EntryDate": "7/25/2014",
    "Division": "ROUTINE-ALT",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Minor Damage or Minor Injury",
    "IncidentDescription": "Driver Nuvia Acevedo was in a accident on 07-14-2014  .Nuvia was not cited  due to the vehicle being on private property but was responsible for causing the accident. There is minor damage on the right side of the vehicle.  The vehicle will be send over to the shop to be observed .Nuvia will be held financially responsible for 30% of the total cost to repair the vehicle up to a maximum of 500.00. This can be deducted from the employee\u0027s paycheck over a period up to four paychecks. Nuvia will receive 3 cm points and will not qualify for the Comtrans Safety Bonus for the year of 2014. ",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "7/25/2014",
    "Points": 30,
    "SupervisorFinished": "",
    "IncidentType": "Safety"
}, {
    "IncidentID": 8099,
    "IncidentDate": "4/29/2014",
    "EntryDate": "5/2/2014",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "Received a Vehicle Inspection from the Resource Department regarding vehicle #439 driver by Nuvia. The vehicle inspection form has undocumented information. This is a note that I spoke with Nuvia Acevedo reminder her that the vehicle inspection must record all information regarding the vehicle that is being driven. Also a reminder to make sure that the vehicle is cleaned upon shift being ended. ",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "5/2/2014",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 7345,
    "IncidentDate": "12/11/2013",
    "EntryDate": "12/16/2013",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Minor Damage or Minor Injury",
    "IncidentDescription": "Driver Nuvia Acevedo was in a accident on 12-11-2013. Nuvia was not cited  but was responsible for causing the accident. Nuvia reports that her foot slip off the brake.  The was no visible damage appearing on the company vehicle.   ",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "12/16/2013",
    "Points": 30,
    "SupervisorFinished": "",
    "IncidentType": "Safety"
}, {
    "IncidentID": 6821,
    "IncidentDate": "9/23/2013",
    "EntryDate": "11/2/2013",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Absence",
    "IncidentDescription": "Nuvia called off for her entire shift.",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Savant, Jamerson",
    "status": "Closed",
    "FinalizedOn": "11/2/2013",
    "Points": 10,
    "SupervisorFinished": "",
    "IncidentType": "Attendance"
}, {
    "IncidentID": 6684,
    "IncidentDate": "8/28/2013",
    "EntryDate": "5/21/2014",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "General Note",
    "IncidentDescription": "Driver lost track of time on cps call.  Supposed to be a 1130 return and driver will not arrive until close to 1155.  Driver was down since 1016.",
    "EmployeeComments": null,
    "Manager": "Mendoza, Luz",
    "Supervisor": "Marshall, Tawana",
    "status": "Closed",
    "FinalizedOn": "5/21/2014",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}, {
    "IncidentID": 6323,
    "IncidentDate": "7/5/2013",
    "EntryDate": "7/19/2013",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Absence",
    "IncidentDescription": "Nuvia went home sick after her second pick up.",
    "EmployeeComments": null,
    "Manager": "Boris, Kolby",
    "Supervisor": "Savant, Jamerson",
    "status": "Closed",
    "FinalizedOn": "7/19/2013",
    "Points": 10,
    "SupervisorFinished": "",
    "IncidentType": "Attendance"
}, {
    "IncidentID": 5797,
    "IncidentDate": "4/9/2013",
    "EntryDate": "4/17/2013",
    "Division": "Routine Field",
    "name": "Acevedo, Nuvia",
    "Shift": "",
    "VehicleNumber": null,
    "NoteType": "Positive Feedback for Performance",
    "IncidentDescription": "Driver volunteered for extra calls!",
    "EmployeeComments": null,
    "Manager": "Boris, Kolby",
    "Supervisor": "Savant, Jamerson",
    "status": "Closed",
    "FinalizedOn": "4/17/2013",
    "Points": 0,
    "SupervisorFinished": "",
    "IncidentType": "Employee Note"
}]

export default cmpahistory

 */